
CREATE EXTENSION IF NOT EXISTS unaccent WITH SCHEMA public;

CREATE TABLE public.discounts (
    id bigint NOT NULL,
    from_date date NOT NULL,
    percentage_of_discount integer NOT NULL,
    to_date date NOT NULL,
    product_id bigint NOT NULL,
    supermarket_id bigint NOT NULL
);

ALTER TABLE public.discounts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.discounts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.grocery_list_items (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    quantity integer NOT NULL,
    grocery_list_id bigint NOT NULL,
    product_id bigint NOT NULL
);

ALTER TABLE public.grocery_list_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.grocery_list_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.grocery_lists (
    id bigint NOT NULL,
    user_id bigint NOT NULL
);

ALTER TABLE public.grocery_lists ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.grocery_lists_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.price_alerts (
    id bigint NOT NULL,
    product_id bigint NOT NULL,
    target_price numeric(12,2) NOT NULL,
    user_id bigint NOT NULL
);

ALTER TABLE public.price_alerts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.price_alerts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.product_prices (
    id bigint NOT NULL,
    currency character varying(255),
    price numeric(38,2) NOT NULL,
    price_date date NOT NULL,
    product_id bigint NOT NULL,
    supermarket_id bigint NOT NULL
);

ALTER TABLE public.product_prices ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.product_prices_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.products (
    id bigint NOT NULL,
    brand character varying(255),
    category character varying(255),
    image_url character varying(255),
    name character varying(255) NOT NULL,
    quantity numeric(38,2),
    unit character varying(255)
);

ALTER TABLE public.products ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.supermarkets (
    id bigint NOT NULL,
    name character varying(255) NOT NULL
);

ALTER TABLE public.supermarkets ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.supermarkets_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.users (
    id bigint NOT NULL,
    email character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    password_hash character varying(255) NOT NULL
);

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.discounts
    ADD CONSTRAINT discounts_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.grocery_list_items
    ADD CONSTRAINT grocery_list_items_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.grocery_lists
    ADD CONSTRAINT grocery_lists_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.price_alerts
    ADD CONSTRAINT price_alerts_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.product_prices
    ADD CONSTRAINT product_prices_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.supermarkets
    ADD CONSTRAINT supermarkets_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.discounts
    ADD CONSTRAINT uk2de4qkn52iqukniggp8jno6ab UNIQUE (product_id, supermarket_id, from_date, to_date);

ALTER TABLE ONLY public.products
    ADD CONSTRAINT uk2rgc8cwxhmbmx4cc6ifm3cys1 UNIQUE (name, brand, category, quantity, unit);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);

ALTER TABLE ONLY public.grocery_lists
    ADD CONSTRAINT ukjs9s0qug5i3jep1bxkvn40oil UNIQUE (user_id);

ALTER TABLE ONLY public.supermarkets
    ADD CONSTRAINT ukmlgspbkyh0xgqqa9xy8sehc79 UNIQUE (name);

ALTER TABLE ONLY public.product_prices
    ADD CONSTRAINT ukn4qijffquxtdtwuiqtlw1nboj UNIQUE (product_id, supermarket_id, price_date);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.discounts
    ADD CONSTRAINT fke3tqxsyxv7qcy8uvf2lns1hx8 FOREIGN KEY (product_id) REFERENCES public.products(id);

ALTER TABLE ONLY public.discounts
    ADD CONSTRAINT fke41fdmtbhutk0mgvtrb9xtu43 FOREIGN KEY (supermarket_id) REFERENCES public.supermarkets(id);

ALTER TABLE ONLY public.product_prices
    ADD CONSTRAINT fkin615tv0nxq3sd7lsce7pacrq FOREIGN KEY (supermarket_id) REFERENCES public.supermarkets(id);

ALTER TABLE ONLY public.grocery_lists
    ADD CONSTRAINT fklso1guk97uhg6gvlf0qc33id4 FOREIGN KEY (user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.product_prices
    ADD CONSTRAINT fko21ew0lemtpkoyly3vm1mq925 FOREIGN KEY (product_id) REFERENCES public.products(id);

ALTER TABLE ONLY public.grocery_list_items
    ADD CONSTRAINT fkpp1qpm8qnc015nqkpj0cmte92 FOREIGN KEY (grocery_list_id) REFERENCES public.grocery_lists(id);

ALTER TABLE ONLY public.grocery_list_items
    ADD CONSTRAINT fkrxo0ar04l2jqwlyvh10avjles FOREIGN KEY (product_id) REFERENCES public.products(id);

ALTER TABLE ONLY public.price_alerts
  ADD CONSTRAINT fk_price_alerts_user FOREIGN KEY (user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.price_alerts
  ADD CONSTRAINT fk_price_alerts_product FOREIGN KEY (product_id) REFERENCES public.products(id);
